# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qw_Z7hAZleV-4T0ryXDp2dxsAXQypauz
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# ── Page config ────────────────────────────────────────────────
st.set_page_config(
    page_title="Crop Price Predictor",
    page_icon="🌾",
    layout="wide"
)

st.title("🌾 APMC Crop Price Predictor")
st.markdown("Predict future mandi prices using LSTM deep learning")

# ── Sidebar controls ───────────────────────────────────────────
st.sidebar.header("Settings")
crop    = st.sidebar.selectbox("Crop",   ["Onion", "Tomato", "Potato"])
market  = st.sidebar.selectbox("Market", ["Lasalgaon", "Pune", "Nashik"])
lookback = st.sidebar.slider("Lookback days", 15, 60, 30)
epochs   = st.sidebar.slider("Training epochs", 10, 100, 50)

# ── Load or generate data ──────────────────────────────────────
@st.cache_data
def load_data(crop_name):
    np.random.seed(42)
    dates  = pd.date_range("2021-01-01", "2024-01-01", freq="D")
    prices = 2000 + np.cumsum(np.random.randn(len(dates)) * 50)
    prices = np.clip(prices, 500, 6000).astype(int)
    df = pd.DataFrame({"date": dates, "modal_price": prices})
    df = df.set_index("date")
    return df

df = load_data(crop)

# ── Feature engineering ────────────────────────────────────────
df['lag_7']       = df['modal_price'].shift(7)
df['lag_14']      = df['modal_price'].shift(14)
df['lag_30']      = df['modal_price'].shift(30)
df['roll_mean_7'] = df['modal_price'].rolling(7).mean()
df['roll_std_7']  = df['modal_price'].rolling(7).std()
df['month']       = df.index.month
df['season']      = df['month'].map({12:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4})
df.dropna(inplace=True)

FEATURES = ['modal_price','lag_7','lag_14','lag_30','roll_mean_7','roll_std_7','month','season']

# ── Show raw data ──────────────────────────────────────────────
with st.expander("📊 View raw price data"):
    st.line_chart(df['modal_price'])
    st.dataframe(df[['modal_price']].tail(10))

# ── Train model ────────────────────────────────────────────────
if st.button("🚀 Train Model & Predict"):
    with st.spinner("Training LSTM model... please wait"):

        scaler = MinMaxScaler()
        scaled = scaler.fit_transform(df[FEATURES])

        def make_sequences(data, lb):
            X, y = [], []
            for i in range(lb, len(data)):
                X.append(data[i-lb:i])
                y.append(data[i, 0])
            return np.array(X), np.array(y)

        X, y  = make_sequences(scaled, lookback)
        split = int(0.8 * len(X))
        X_train, X_test = X[:split], X[split:]
        y_train, y_test = y[:split], y[split:]

        model = Sequential([
            LSTM(64, return_sequences=True,
                 input_shape=(lookback, len(FEATURES))),
            Dropout(0.2),
            LSTM(32),
            Dropout(0.2),
            Dense(16, activation='relu'),
            Dense(1)
        ])
        model.compile(optimizer='adam', loss='mse')
        es = EarlyStopping(patience=10, restore_best_weights=True)
        model.fit(X_train, y_train, epochs=epochs, batch_size=32,
                  validation_split=0.1, callbacks=[es], verbose=0)

        y_pred = model.predict(X_test)

        def to_price(vals):
            dummy = np.zeros((len(vals), len(FEATURES)))
            dummy[:, 0] = vals.flatten()
            return scaler.inverse_transform(dummy)[:, 0]

        actual    = to_price(y_test)
        predicted = to_price(y_pred)

        rmse = np.sqrt(mean_squared_error(actual, predicted))
        mae  = mean_absolute_error(actual, predicted)

    # ── Metrics ────────────────────────────────────────────────
    st.success("Model trained successfully!")
    col1, col2, col3 = st.columns(3)
    col1.metric("RMSE",  f"₹ {rmse:.0f}")
    col2.metric("MAE",   f"₹ {mae:.0f}")
    col3.metric("Accuracy", f"{100 - (mae/actual.mean()*100):.1f}%")

    # ── Chart ──────────────────────────────────────────────────
    st.subheader(f"📈 {crop} Price — Actual vs Predicted ({market})")
    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(actual,    label="Actual price",    color="#2E86AB")
    ax.plot(predicted, label="Predicted price",
            color="#F6AE2D", linestyle="--")
    ax.set_xlabel("Days")
    ax.set_ylabel("Price (₹/quintal)")
    ax.legend()
    ax.grid(alpha=0.3)
    st.pyplot(fig)

    # ── Next 7 days forecast ───────────────────────────────────
    st.subheader("🔮 Next 7-day Price Forecast")
    last_seq  = scaled[-lookback:].reshape(1, lookback, len(FEATURES))
    forecasts = []
    seq = last_seq.copy()
    for _ in range(7):
        pred = model.predict(seq, verbose=0)[0, 0]
        forecasts.append(pred)
        new_row       = seq[0, -1, :].copy()
        new_row[0]    = pred
        seq           = np.append(seq[:, 1:, :],
                                  new_row.reshape(1, 1, -1), axis=1)

    dummy = np.zeros((7, len(FEATURES)))
    dummy[:, 0] = forecasts
    forecast_prices = scaler.inverse_transform(dummy)[:, 0]

    forecast_df = pd.DataFrame({
        "Day"          : [f"Day {i+1}" for i in range(7)],
        "Predicted Price (₹/quintal)": forecast_prices.astype(int)
    })
    st.dataframe(forecast_df, use_container_width=True)

st.sidebar.markdown("---")
st.sidebar.info("Built with LSTM + Streamlit\nData: APMC / Agmarknet")
